// lib/canonicalize-region-paths 单元测试：产物里的 `//#region` 行必须与 process.cwd() 无关。
//
// 为什么单独测（而不是只靠各包的 freshness 门）：那两道门比的是「同一进程内两侧同形」，
// 换 cwd 时两侧一起漂移 ⇒ 门照样绿。真正的判据是「两种 cwd 下的字节相等」，只有把两种
// 实测形态当夹具钉在这里才咬得住。
//
// 夹具取的是实测到的真实形态（session-rescue 的 host/client 与 shared 自身），不是编出来的形状。
import { describe, it } from "vitest";
import assert from "node:assert/strict";
import { canonicalizeRegionPaths } from "../lib/canonicalize-region-paths.ts";

/** 包根绝对路径（builder 侧就是 import.meta.dirname）。 */
const PKG_DIR = "/repo/plugins/session-rescue";

/** 产物里的一行真代码：用来证明「非 region 字节一个不动」。 */
const CODE_LINE = "const a = 1;";

/** 产物首行的生成说明（builder 写的，不参与正典化）。 */
const GENERATED_BANNER = "// GENERATED by build-host.mjs";

/**
 * 拼一段产物文本（说明行 + 逐行 region 标记 + 一行真代码）。
 * @param marks - 各模块路径，按 rolldown 的写法逐条成行
 * @returns 可直接喂给被测函数的多行文本
 */
function artifactOf(marks: string[]): string {
  const rows = marks.map((mark) => `//#region ${mark}`);
  return [GENERATED_BANNER, ...rows, CODE_LINE].join("\n");
}

/**
 * 抽出产物文本里的全部 `//#region` 行。
 * @param code - 产物文本
 * @returns 命中的行
 */
function regionLines(code: string): string[] {
  return code.split("\n").filter((line) => line.startsWith("//#region"));
}

/**
 * 造一段产物、折成 canonical、只回 region 行（各用例的主判据形态）。
 * @param marks - 某个 cwd 下 rolldown 实际写出的模块路径
 * @param pkgDir - 交给被测函数的包根（默认本文件顶上的那枚）
 * @returns 折完之后的 region 行
 */
function foldedRegionLines(marks: string[], pkgDir: string = PKG_DIR): string[] {
  const folded = canonicalizeRegionPaths(artifactOf(marks), pkgDir);
  return regionLines(folded);
}

describe("带包名前缀的行 ⇒ 折回相对包根", () => {
  it("cwd = plugins/ 的形态 ⇒ 前缀消失", () => {
    const folded = foldedRegionLines(["session-rescue/lib/failure-classify.ts"]);
    assert.deepEqual(folded, ["//#region lib/failure-classify.ts"]);
  });

  it("cwd = 包根的形态 ⇒ 逐字节不变", () => {
    const current = artifactOf(["lib/turn-facts.ts"]);
    assert.equal(canonicalizeRegionPaths(current, PKG_DIR), current);
  });

  it("两处 cwd 的实测形态折完 ⇒ 两串相等（可复现性的正面判据）", () => {
    const fromPkgCwd = artifactOf(["host.ts", "lib/resume-scheduler.ts"]);
    const fromPluginsCwd = artifactOf([
      "session-rescue/host.ts",
      "session-rescue/lib/resume-scheduler.ts",
    ]);
    const pkgFolded = canonicalizeRegionPaths(fromPkgCwd, PKG_DIR);
    const pluginsFolded = canonicalizeRegionPaths(fromPluginsCwd, PKG_DIR);
    assert.equal(pkgFolded, pluginsFolded);
  });

  it("工作区根当 cwd 时是两段前缀 ⇒ 一并折回", () => {
    const folded = foldedRegionLines(["plugins/session-rescue/turn-review.ts"]);
    assert.deepEqual(folded, ["//#region turn-review.ts"]);
  });

  it("cwd = DSH_HOME 时的跨包依赖多一段父目录 ⇒ 只收父目录段", () => {
    const folded = foldedRegionLines(["plugins/shared/lib/errors.ts"]);
    assert.deepEqual(folded, ["//#region shared/lib/errors.ts"]);
  });

  it("锚点只认行首：路径中段的 plugins 不参与收折", () => {
    const current = artifactOf(["node_modules/webpack/plugins/index.js"]);
    assert.equal(canonicalizeRegionPaths(current, PKG_DIR), current);
  });

  it("包名只按整段匹配：文件名恰为包名时不是前缀命中", () => {
    const current = artifactOf(["lib/session-rescue.ts"]);
    assert.equal(canonicalizeRegionPaths(current, PKG_DIR), current);
  });
});

describe("行首相对段折叠：跨包依赖在两种 cwd 下同形", () => {
  it("../shared 与同级的 shared ⇒ 折完相等", () => {
    const fromPkgCwd = foldedRegionLines(["../shared/lib/record.ts"]);
    const fromPluginsCwd = foldedRegionLines(["shared/lib/record.ts"]);
    assert.deepEqual(fromPkgCwd, fromPluginsCwd);
    assert.deepEqual(fromPkgCwd, ["//#region shared/lib/record.ts"]);
  });

  it("../node_modules 与 ./node_modules ⇒ 都收成裸 node_modules", () => {
    const fromParent = foldedRegionLines(["../node_modules/x/index.js"]);
    const fromSelf = foldedRegionLines(["./node_modules/y/index.cjs"]);
    assert.deepEqual(fromParent, ["//#region node_modules/x/index.js"]);
    assert.deepEqual(fromSelf, ["//#region node_modules/y/index.cjs"]);
  });

  it("连续多枚行首相对段也一次收尽", () => {
    const folded = foldedRegionLines(["../../shared/lib/locale.ts"]);
    assert.deepEqual(folded, ["//#region shared/lib/locale.ts"]);
  });

  it("包名前缀与行首相对段同时出现（sibling cwd）⇒ 先折叠再折前缀", () => {
    const folded = foldedRegionLines(["../session-rescue/src/ui-messages.ts"]);
    assert.deepEqual(folded, ["//#region src/ui-messages.ts"]);
  });
});

describe("射程只有 //#region 那一行的路径文本", () => {
  it("//#endregion 与非 region 行原样保留", () => {
    const code = ["//#endregion", "  const b = 2;", "//#regionless host.ts"].join("\n");
    assert.equal(canonicalizeRegionPaths(code, PKG_DIR), code);
  });

  it("代码中间的同形字符串不被改写（判据是整行行首）", () => {
    const line = String.raw`  const note = "//#region session-rescue/lib/messages.ts";`;
    assert.equal(canonicalizeRegionPaths(line, PKG_DIR), line);
  });

  it("生成说明行与真代码行不参与改写", () => {
    const folded = canonicalizeRegionPaths(artifactOf(["session-rescue/lib/messages.ts"]), PKG_DIR);
    const rows = folded.split("\n");
    assert.equal(rows[0], GENERATED_BANNER, "GENERATED 说明行被改写了");
    assert.equal(rows.at(-1), CODE_LINE, "真代码行被改写了");
  });

  it("换行为 CRLF 时行尾不丢", () => {
    const code = ["//#region session-rescue/lib/jsonl.ts", CODE_LINE].join("\r\n");
    const expected = ["//#region lib/jsonl.ts", CODE_LINE].join("\r\n");
    assert.equal(canonicalizeRegionPaths(code, PKG_DIR), expected);
  });
});

describe("包根字符串的边界形状", () => {
  it("pkgDir 末段带分隔符 ⇒ 与不带时同一结果", () => {
    const code = artifactOf(["session-rescue/lib/errors.ts"]);
    const withSeparator = canonicalizeRegionPaths(code, `${PKG_DIR}/`);
    const withoutSeparator = canonicalizeRegionPaths(code, PKG_DIR);
    assert.equal(withSeparator, withoutSeparator);
  });

  it("pkgDir 没有分隔符 ⇒ 整串当包名", () => {
    const folded = foldedRegionLines(["lesson-loop/host.ts"], "lesson-loop");
    assert.deepEqual(folded, ["//#region host.ts"]);
  });

  it("pkgDir 只剩分隔符 ⇒ 无从取名，整串原样交回", () => {
    const code = artifactOf(["session-rescue/lib/http.ts"]);
    assert.equal(canonicalizeRegionPaths(code, "/"), code);
    assert.equal(canonicalizeRegionPaths(code, "\\"), code);
  });

  it("shared 自己的产物：段名里的 shared 不是段边界 ⇒ 不误折", () => {
    // `@jayyuen66/dsh-plugin-shared` 与 `dsh-brand` 都只以**子串**含包名，整段匹配不命中，
    // 于是本用例只有行首的 `../` 被收掉，路径的其余部分一字不动。
    const expected = artifactOf([
      "node_modules/@jayyuen66/dsh-plugin-shared/lib/index.js",
      "node_modules/.pnpm/@deepseek-ai+dsh-brand@0.2.0/node_modules/@deepseek-ai/dsh-brand/lib/index.js",
    ]);
    const folded = canonicalizeRegionPaths(
      artifactOf([
        "../node_modules/@jayyuen66/dsh-plugin-shared/lib/index.js",
        "../node_modules/.pnpm/@deepseek-ai+dsh-brand@0.2.0/node_modules/@deepseek-ai/dsh-brand/lib/index.js",
      ]),
      "/repo/plugins/shared",
    );
    assert.equal(folded, expected);
  });
});

describe("幂等", () => {
  it("对 canonical 文本二次调用逐字符不变", () => {
    const marks = [
      "session-rescue/lib/dock-state.ts",
      "../shared/lib/card-apply.ts",
      "node_modules/.pnpm/@deepseek-ai+dsh-jobs@0.2.0/index.js",
    ];
    const once = canonicalizeRegionPaths(artifactOf(marks), PKG_DIR);
    const twice = canonicalizeRegionPaths(once, PKG_DIR);
    assert.equal(twice, once);
    assert.equal(canonicalizeRegionPaths(twice, PKG_DIR), once);
  });

  it("空文本与无 region 行的文本都是自身不动点", () => {
    assert.equal(canonicalizeRegionPaths("", PKG_DIR), "");
    const plain = `${CODE_LINE}\n`;
    assert.equal(canonicalizeRegionPaths(plain, PKG_DIR), plain);
  });
});
