#!/usr/bin/env node
/// <reference types="node" />
// 构建 dist/*.js：rolldown 把源文件打成 ESM（node 目标，node: 内建自动外部化）。
// 为什么必须有这一步：Node 对 node_modules 里的 .ts 直接抛
// ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING（实测），而发布出去的包正是躺在
// node_modules 里被 dsh 载入的——官方包入口也一律是编译产物（packages/bundle/base
// 的 main 就是 lib/index.js）。本仓源码住在 lib/ 下，故产物落 dist/，不与源码混目录。
// 类型产物：各切面由 tsc -p tsconfig.build.json 出 dist/types/*.d.ts；barrel 的
// d.ts 在此生成——源码里 `export * from "./http.ts"` 是类型剥离形态所需，原样进
// d.ts 会让消费方解析不到（.ts 不是可解析的类型说明符），故重写成 ./types/x.js。
// 顶部 node reference：oxlint 类型检查对 .mjs 不自动加载 @types/node，需显式声明
// 才能解析 node:fs/promises、process、import.meta（否则整文件按 error 类型误报 unsafe）。
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { rolldown } from "rolldown";
import { canonicalizeRegionPaths } from "./lib/canonicalize-region-paths.ts";

const root = import.meta.dirname;
const outDir = path.join(root, "dist");
/** @type {unknown} */
const pkgJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));

/**
 * 从 JSON.parse 的 unknown 投影为 Record（非对象 → 空对象兜底），避免 any 索引。
 * @param {unknown} raw
 * @returns {Record<string, unknown>}
 */
function asRecord(raw) {
  if (raw !== null && typeof raw === "object" && !Array.isArray(raw)) {
    return raw;
  }
  return {};
}

/**
 * 取依赖表里的包名清单（值即外部化说明符）。
 * @param {string} field
 * @returns {string[]}
 */
function dependencyNames(field) {
  const table = asRecord(asRecord(pkgJson)[field]);
  return Object.keys(table).filter((name) => typeof table[name] === "string");
}

// 与全部兄弟包同一条口径：dependencies/peerDependencies 一律外部化，
// 产物里保留裸说明符。shared 曾是**唯一**没有 external 选项的 build-host.mjs，理由是
// "本机运行面走源码不走 dist"——那句只对了一半：本包是**发布件**，消费方装的是躺在
// node_modules 里的 dist/，那边没有源码可走。不外部化就把官方
// `truncateWithoutSplittingSurrogatePair` 的函数体复制进 shared 的 chunk，于是同一进程里
// 官方截断件有两份身份（宿主一份 + shared dist 一份），而 shared 自己还要为它的行为负责。
// external 的字符串项是精确匹配，子路径说明符会漏 ⇒ 按「包名段」判定而不是枚举名字。
const externalNames = new Set([
  ...dependencyNames("dependencies"),
  ...dependencyNames("peerDependencies"),
]);

/**
 * 说明符的包名段：`@scope/pkg/sub` → `@scope/pkg`，`pkg/sub` → `pkg`。
 * @param {string} id
 * @returns {string}
 */
function packageNameOf(id) {
  const segments = id.split("/");
  if (id.startsWith("@")) {
    return segments.slice(0, 2).join("/");
  }
  return segments[0] ?? id;
}

/**
 * rolldown 外部化判据。
 * @param {string} id
 * @returns {boolean}
 */
const isExternal = (id) => externalNames.has(packageNameOf(id));

/** 各切面（消费方按子路径取，谁也不必为别人的依赖买单）。 */
const facets = [
  "http",
  "tool-events",
  "card-apply",
  "project-key",
  "locale",
  "lesson-bus",
  "text",
  "record",
  "errors",
  "jsonl",
  "job-outcome",
  "trust",
];

/** barrel 之外还要单独出的入口：lib/index.ts 聚合同运行时行为。
 *  `canonicalize-region-paths` 不进 barrel——它是 builder 期的文本后处理件，塞进根导入面
 *  会让每个运行时消费方都为它付一次导入；各包 build-*.mjs 按子路径取用。 */
const entries = [
  "lib/index.ts",
  ...facets.map((facet) => `lib/${facet}.ts`),
  "lib/canonicalize-region-paths.ts",
];

/** barrel 的类型文件文本（指向 tsc 产出的各切面 d.ts）。 */
function barrelTypes() {
  return [
    "// GENERATED by build-host.mjs — 源形态的 `./x.ts` 说明符进 d.ts 后无法解析，故重写。",
    ...facets.map((facet) => `export * from "./types/${facet}.js";`),
    "",
  ].join("\n");
}

/**
 * 落盘项（元组而非数组，Map 构造才拿到 [路径, 文本] 的类型）。
 * @param {string} file
 * @param {string} code
 * @returns {[string, string]}
 */
function artifact(file, code) {
  return [file, code];
}

/**
 * 打出全部入口，返回「落盘绝对路径 → 文件文本」。多入口由 rolldown 自动
 * code-split，共用实现只落一份 chunk。
 * @returns {Promise<Map<string, string>>}
 */
export async function buildHost() {
  const bundle = await rolldown({
    input: entries.map((entry) => path.join(root, entry)),
    platform: "node",
    external: isExternal,
    resolve: { extensions: [".ts", ".mjs", ".js"] },
  });
  const { output } = await bundle.generate({
    format: "esm",
    entryFileNames: "[name].js",
    chunkFileNames: "[name]-[hash].js",
  });
  const chunks = output.filter((item) => item.type === "chunk");
  if (chunks.length === 0) {
    throw new Error("rolldown generate returned no chunk output");
  }
  // `//#region` 行的路径由 rolldown 按 process.cwd() 算出 ⇒ 同一份源码有两种字节。折 canonical
  // 落在返回值之前（test/host-freshness.ts 比的是内存 Map 与磁盘 dist 两侧），写盘那一侧不再是
  // 唯一的正典化点。
  const files = chunks.map((chunk) =>
    artifact(path.join(outDir, chunk.fileName), canonicalizeRegionPaths(chunk.code, root)),
  );
  files.push(artifact(path.join(outDir, "index.d.ts"), barrelTypes()));
  return new Map(files);
}

async function main() {
  await mkdir(outDir, { recursive: true });
  const built = await buildHost();
  const artifacts = [...built.entries()];
  await Promise.all(artifacts.map(([file, code]) => writeFile(file, code, "utf8")));
  console.info("host built:", artifacts.length, "files -> dist/");
}

if (process.argv[1] === import.meta.filename) {
  try {
    await main();
  } catch (error) {
    console.error(error);
    process.exitCode = 1;
  }
}
