#!/usr/bin/env node
/// <reference types="node" />
// 构建 dist/*.js：rolldown 把源文件打成 ESM（node 目标，node: 内建自动外部化）。
// 为什么必须有这一步：Node 对 node_modules 里的 .ts 直接抛
// ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING（实测），而发布出去的包正是躺在
// node_modules 里被 dsh 载入的——官方包入口也一律是编译产物（packages/bundle/base
// 的 main 就是 lib/index.js）。本仓源码住在 lib/ 下，故产物落 dist/，不与源码混目录。
// 类型产物：各切面由 tsc -p tsconfig.build.json 出 dist/types/*.d.ts；barrel 的
// d.ts 在此生成——源码里 `export * from "./http.ts"` 是类型剥离形态所需，原样进
// d.ts 会让消费方解析不到（.ts 不是可解析的类型说明符），故重写成 ./types/x.js。
// 顶部 node reference：oxlint 类型检查对 .mjs 不自动加载 @types/node，需显式声明
// 才能解析 node:fs/promises、process、import.meta（否则整文件按 error 类型误报 unsafe）。
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { rolldown } from "rolldown";
import { canonicalizeRegionPaths } from "./lib/canonicalize-region-paths.ts";
import { createIsExternal } from "./build-shared.mjs";

const root = import.meta.dirname;
const outDir = path.join(root, "dist");

// 四件机械件（asRecord / dependencyNames / packageNameOf / isExternal）与外部化口径都收在
// build-shared.mjs——此前这里与 build-config.mjs 各有一份逐字节相同的副本。
const isExternal = await createIsExternal(root);

/** 各切面（消费方按子路径取，谁也不必为别人的依赖买单）。 */
const facets = [
  "http",
  "tool-events",
  "card-apply",
  "project-key",
  "locale",
  "lesson-bus",
  "text",
  "record",
  "errors",
  "jsonl",
  "job-outcome",
  "trust",
];

/** barrel 之外还要单独出的入口：lib/index.ts 聚合同运行时行为。
 *  `canonicalize-region-paths` 不进 barrel——它是 builder 期的文本后处理件，塞进根导入面
 *  会让每个运行时消费方都为它付一次导入；各包 build-*.mjs 按子路径取用。 */
const entries = [
  "lib/index.ts",
  ...facets.map((facet) => `lib/${facet}.ts`),
  "lib/canonicalize-region-paths.ts",
];

/** barrel 的类型文件文本（指向 tsc 产出的各切面 d.ts）。 */
function barrelTypes() {
  return [
    "// GENERATED by build-host.mjs — 源形态的 `./x.ts` 说明符进 d.ts 后无法解析，故重写。",
    ...facets.map((facet) => `export * from "./types/${facet}.js";`),
    "",
  ].join("\n");
}

/**
 * 落盘项（元组而非数组，Map 构造才拿到 [路径, 文本] 的类型）。
 * @param {string} file
 * @param {string} code
 * @returns {[string, string]}
 */
function artifact(file, code) {
  return [file, code];
}

/**
 * 打出全部入口，返回「落盘绝对路径 → 文件文本」。多入口由 rolldown 自动
 * code-split，共用实现只落一份 chunk。
 * @returns {Promise<Map<string, string>>}
 */
export async function buildHost() {
  const bundle = await rolldown({
    input: entries.map((entry) => path.join(root, entry)),
    platform: "node",
    external: isExternal,
    resolve: { extensions: [".ts", ".mjs", ".js"] },
  });
  const { output } = await bundle.generate({
    format: "esm",
    entryFileNames: "[name].js",
    chunkFileNames: "[name]-[hash].js",
    // 压缩：实测同一批 14 个入口 35,020 B -> 10,345 B（省 70.5%）。本包的 dist 就是发布形态，
    // 消费方把它当 external 直接 import（不再二次打包），所以这些字节是真实装载成本。
    // 官方根 tsdown.config.ts 同样没开 minify，但那是 monorepo 内消费，与这里的处境不同。
    // 唯一变大的入口是 barrel（1,300 -> 1,523 B）：oxc 会把 re-export 的具名清单展开。
    // +223 B 换 24 KB 缩减，划算。
    minify: true,
  });
  const chunks = output.filter((item) => item.type === "chunk");
  if (chunks.length === 0) {
    throw new Error("rolldown generate returned no chunk output");
  }
  // `//#region` 行的路径由 rolldown 按 process.cwd() 算出 ⇒ 同一份源码有两种字节。折 canonical
  // 落在返回值之前（test/host-freshness.ts 比的是内存 Map 与磁盘 dist 两侧），写盘那一侧不再是
  // 唯一的正典化点。
  //
  // 开了 minify 之后这步对本包自己的产物是空转：压缩会剥掉 region 注释，实测 14 个 chunk 里
  // 仍含 "//#region" 字样的那一个只是 canonicalize-region-paths.js 里正则的字面量，不是标记。
  // 保留调用是因为它无成本、且 9 个兄弟包的 build-*.mjs 仍在未压缩的产物上真正依赖它；
  // 万一将来关掉 minify，这一步立刻重新生效，不必回头改这里。
  const files = chunks.map((chunk) =>
    artifact(path.join(outDir, chunk.fileName), canonicalizeRegionPaths(chunk.code, root)),
  );
  files.push(artifact(path.join(outDir, "index.d.ts"), barrelTypes()));
  return new Map(files);
}

async function main() {
  await mkdir(outDir, { recursive: true });
  const built = await buildHost();
  const artifacts = [...built.entries()];
  await Promise.all(artifacts.map(([file, code]) => writeFile(file, code, "utf8")));
  console.info("host built:", artifacts.length, "files -> dist/");
}

if (process.argv[1] === import.meta.filename) {
  try {
    await main();
  } catch (error) {
    console.error(error);
    process.exitCode = 1;
  }
}
